### ISSUE TITLE
pip install missing `__init__.py` in `jaraco` module?

### ISSUE THREAD

**Issue by dmlb2000** [jaraco/jaraco.classes#2]
Not sure what happened but recently we've ran into a bug with this module, behind CherryPy.

```
Traceback (most recent call last):
File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/opt/cartd/virtualenv/lib/python2.7/site-packages/celery/__main__.py", line 18, in <module>
main()
File "/opt/cartd/virtualenv/lib/python2.7/site-packages/celery/__main__.py", line 14, in main
_main()
File "/opt/cartd/virtualenv/lib64/python2.7/site-packages/celery/bin/celery.py", line 326, in main
cmd.execute_from_commandline(argv)
File "/opt/cartd/virtualenv/lib64/python2.7/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
super(CeleryCommand, self).execute_from_commandline(argv)))
File "/opt/cartd/virtualenv/lib64/python2.7/site-packages/celery/bin/base.py", line 279, in execute_from_commandline
argv = self.setup_app_from_commandline(argv)
File "/opt/cartd/virtualenv/lib64/python2.7/site-packages/celery/bin/base.py", line 481, in setup_app_from_commandline
self.app = self.find_app(app)
File "/opt/cartd/virtualenv/lib64/python2.7/site-packages/celery/bin/base.py", line 503, in find_app
return find_app(app, symbol_by_name=self.symbol_by_name)
File "/opt/cartd/virtualenv/lib64/python2.7/site-packages/celery/app/utils.py", line 355, in find_app
sym = symbol_by_name(app, imp=imp)
File "/opt/cartd/virtualenv/lib64/python2.7/site-packages/celery/bin/base.py", line 506, in symbol_by_name
return imports.symbol_by_name(name, imp=imp)
File "/opt/cartd/virtualenv/lib64/python2.7/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
module = imp(module_name, package=package, **kwargs)
File "/opt/cartd/virtualenv/lib64/python2.7/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
return imp(module, package=package)
File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
__import__(name)
File "cart/__init__.py", line 10, in <module>
import cherrypy
File "/opt/cartd/virtualenv/lib64/python2.7/site-packages/cherrypy/__init__.py", line 66, in <module>
from ._cperror import (
File "/opt/cartd/virtualenv/lib64/python2.7/site-packages/cherrypy/_cperror.py", line 128, in <module>
from jaraco.classes.properties import classproperty
ImportError: No module named jaraco.classes.properties
```
This interaction is with cherrypy and celery somehow. The cherrypy isn't getting called to start anything it's just getting imported. I did notice that the `jaraco` module is just an empty directory, this traceback gets resolved when I touch `__init__.py` in the `jaraco` directory. I thought that makes a proper python module out of the directory which is why the stack dump is happening.

This is getting invoked by importing cherrypy when starting celery, though not executing anything internal to cherrypy.

So I guess the bug is why is `__init__.py` not in the jaraco directory for this package when downloaded using pip?

**Comment by dmlb2000** [comment]
So the `jaraco` module is actually a namespace and my guess is that celery is doing something stupid with imports to break this functionality of python...

**Comment by benjaoming** [comment]
Is it possible for CherryPy to drop this dependency and internalize it?

Namespaced packages are hard to support, I think both Pex, CherryPy and other mechanisms of installing packages to a target suffer from this shortcoming of support.

**Comment by benjaoming** [comment]
Reference for Pex' issues with this: https://github.com/pantsbuild/pex/issues/393

**Comment by jaraco** [comment]
> Is it possible for CherryPy to drop this dependency and internalize it?

It's possible, but doing so would effectively blacklist all namespace packages from use in any popular package or any package that wishes to be popular.

I would very much like not to have to blacklist namespace packages. It's true that the way namespace packages are defined and installed is to omit the `__init__.py` file and instead provide native support (Python 3.5+) or have a compatibility hook (the `-nspkg.pth` file) for older Pythons.

But since pip installs those things properly, the packages themselves should work fine:

```
$ python -m venv issues-2
Collecting jaraco.classes
  Using cached jaraco.classes-1.4.3-py2.py3-none-any.whl
Collecting six (from jaraco.classes)
  Using cached six-1.11.0-py2.py3-none-any.whl
Installing collected packages: six, jaraco.classes
Successfully installed jaraco.classes-1.4.3 six-1.11.0
$ issues-2/bin/python -c "import jaraco.classes.properties"
$ cat issues-2/lib/python3.6/site-packages/jaraco.classes-1.4.3-py3.6-nspkg.pth 
import sys, types, os;has_mfs = sys.version_info > (3, 5);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('jaraco',));importlib = has_mfs and __import__('importlib.util');has_mfs and __import__('importlib.machinery');m = has_mfs and sys.modules.setdefault('jaraco', importlib.util.module_from_spec(importlib.machinery.PathFinder.find_spec('jaraco', [os.path.dirname(p)])));m = m or sys.modules.setdefault('jaraco', types.ModuleType('jaraco'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p)
$ ls issues-2/lib/python3.6/site-packages/jaraco                            
classes
```

AFAIK, this package (and other jaraco.* and keyrings.* packages) is doing all the right things to support namespace packages.

Years ago, I would have been more hesitant to introduce namespace packages to a project's dependencies because of the cases where they weren't supported. If we continue to pull those packages from the dependency chain, those projects (celery, pex) won't have any incentive to fix the bug. Indeed, it sort-of feels like the request here is for me to relegate all namespace packages to second class status in perpetuity.

Given that namespace packages have been a concept for a long time and that the [jaraco namespace has been around for most of a decade](https://github.com/jaraco/jaraco.util/tree/52348a76b4e67711f9c9abe29d77751e50270f4b), and given that namespace packages are a standard baked into Python, I think it really makes sense for these alternate packaging systems to fix thee issues they have with supporting these packages.

If you have constructive comments, I'm happy to help, but as filed, this ticket is essentially a request to withdraw this project, which is a non-starter.

**Comment by benjaoming** [comment]
Hi @jaraco !

Sorry, I thought it would be a more simple decision to internalize this dependency -- not sure if you maintain this code separately from CherryPy for other reasons? I guess you do since you went ahead and create the repository and the namespace! However, just want to point out -- and this not trying to be rude -- because I know you make really HUGE contributions to CherryPy, and to so many other things.... just can't help but notice:

Repo has 0 stars
Only you watching the it
CherryPy only imports this dependency in 1 line
Code that's imported amounts to 29 lines

    cherrypy/_cperror.py
    128:from jaraco.classes.properties import classproperty

For a fairly large project like CherryPy, this is not the kind of dependency, I'd normally recommend.

I'm not suggesting that you withdraw your project, and I appreciate the good work you folks do with CherryPy - but I would think it seemed like a decent refactor to just move this `classproperty` over to CherryPy and have 1 dependency less :)

I'll do a PR in the CherryPy repository, seems like an easier way to grasp how bad this `classproperty` would sit as an internal component.

We had to revert back to CherryPy 11 because of this issue for now -- we could also write a patch that injects `__init__.py` in to the `jaraco/` folder. But for now, I just leave this PR around, and then you and the others in CherryPy can decide.

**Comment by jaraco** [comment]
I will be reluctant to accept a PR to CherryPy until there's at least a ticket upstream indicating why CherryPy is copy/pasting code rather than requiring it (such that one could eventually drop the redundant code).

**Comment by benjaoming** [comment]
I hear what you're saying that this lack of namespacing support is regretful, but I'm just not motivated to put in upstream issues because of `jaraco.classes`, maybe some other more vital structure... but this seems almost silly, like you wanted this `@classproperty` (and that's fine, it's used once in CherryPy, but the idea is nice)... but why is the namespacing necessary for this? Others don't go around namespacing their packages, so what's the argument here that CherryPy needs a namespaced package to have this `@classproperty` that you copied from Stack Overflow? :)

**Comment by jaraco** [comment]
> why is the namespacing necessary for this?

Well, in part, because this package is the one place that I'm aware of that supplies this functionality in a published package. If this functionality were published elsewhere, I'd happily deprecate the usage here and defer to someone else's contribution. I use namespace packages to publish my packages so that I don't spam PyPI with dozens of packages. I have 48 packages in GitHub and PyPI in the `jaraco`. I'm also a maintainer of several other packages that are in namespaces (`backports`, `svg`, `yg`, `keyrings`). Moreover, I drew this concept from experience in Java and working with other Python packages such as Zope. I think it would be disrespectful of me to lay claim to dozens of top-level names when one will suffice, especially for these modest packages.

It would be a crazy amount of work to deprecate the use of namespaces for what's implied herein - that namespace packages are essentially non-viable in popular packages.

I have more to say from the CherryPy perspective, so I'll say that in the PR.

**Comment by jaraco** [comment]
> this [implementation] that you copied from Stack Overflow

I'd like to point out that this implementation that you're besmirching in your comment, is something which I [worked on originally in 2009](https://stackoverflow.com/a/1383402/70170), deriving from raw specifications.

But the value of having something like this in a package is that it can be refined and evolve and the benefits get re-used. When the code is simply copied from StackOverflow into each and every project, each copy becomes a fork and an improvement on the approach in one won't be applied to the other. I have codebases where I had originally copied the code from my StackOverflow answer and later replaced that call with this, better implementation. I offer that benefit to other projects, and that's why I'm inclined to utilize it in projects like CherryPy.

**Comment by benjaoming** [comment]
Okay so then my opinion about namespaced packages... although I mostly just want a bug fixed :)

Firstly, thanks for the thoughtful response and elaboration. I understand now how namespaced packages have evolved into a strategy and method for distributing smaller chunks of code, with the potential to better maintain and optimize popularly shared code fragments. I'm very much against these huge `utils` or `shared` monolith libraries, so I get why this can be nicer.

On the more optimistic side, I'd say that these popular code fragments rarely cause problems. Don't remember encountering any myself. For instance `lru_cache`, I always just copy-pasted from Django. Never had issues. This function was then finally added to `functools` in Python 3, moreover it never had any real maintenance for the 4 years it sat in the Django repo. This could also be the path for `@classproperty`.

Would you have wanted Django to add a dependency for `lru_cache` in 2013-2017? I would think they were out of their minds if they added a dependency for this small function, giving all the test responsibility and security risks implied to 1 person. See its short history here: https://github.com/django/django/commits/master/django/utils/lru_cache.py

For this distribution mechanism to work in principle, there would have to be more active maintainers. Otherwise it's a gaping security hole with lots of bus factor. You can't have lots of small namespaced packages in large, popular projects if they aren't nursed. Consider maybe talking to jazzband.co about some community-driven utility namespace.

**Comment by jaraco** [comment]
I agree - there is a bit of a security issue here and a general maintenance risk, akin to the one that [bit node developers last year](https://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/).

I've always been concerned about the bus factor and I joined Jazzband early on because I'd like the idea of there being a community around incubating and low-usage libraries. I had planned to move one repository there and see how that went, but looking at the repo list, I don't see any projects I maintain there. I don't recall if I ran into a specific issue or if I just didn't get around to moving a project.

> Would you have wanted Django to add a dependency for lru_cache in 2013-2017?

I think I would have. Instead what you get is another copy of code from a post. This one happened to be stable, but it also appears as if it never worked around the bugs in update_wrapper, which the [published backport did](/jaraco/backports.functools_lru_cache/commit/7f8725325ee8c275e80a28420a962128e0fc6afd). By keeping the backport available only in Django, they leave the non-Django community without a solution. Other projects follow this pattern and you end up with dozens of projects with their own copy of the code, each diverging slightly to suit the needs and whims of that project, and all vulnerable to software erosion as there's no place the backport is reliably maintained across projects.

If someone on the Django project had published the backport, I would have used that rather than publishing it myself.

I find forks and divergent implementations to be one of the most challenging aspects of maintaining mature, enterprise-grade Python projects.

> This could also be the path for `@classproperty`.

I agree it sometimes makes sense to temporarily copy code into a project rather than involve a new dependency. And in fact, for a long time, CherryPy had no dependencies, which made it particularly friendly to fresh Python developers who hadn't yet grasped the nuances of Python Packaging. But the packaging situation has improved dramatically and CherryPy now relies on that infrastructure. But even in the case where the code is copied rather than linked, it's worthwhile to have a canonical source where that code is maintained, so that issues can be filed and resolved and the history can be tracked.

I try to remain humble when it comes to this functionality. In fact, when I identify a project like `more_itertools` that has substantial overlap with projects I've created like `jaraco.itertools`, I seek to [consolidate those efforts](https://github.com/erikrose/more-itertools/issues/32), deferring to the more popular and more broadly-maintained package.

I'd do the same for the `@classproperty` or all of `jaraco.classes` if I stumbled across a relevant implementation.

Still, I think the security and custody and maintenance issues are outside the scope of this ticket.

**Comment by benjaoming** [comment]
*Going into total chat mode here*

I think `@classproperty` is needed in Python, but it takes a lot of time to dig around in bugs.python.org. Do you know of any existing open discussion?

> I find forks and divergent implementations to be one of the most challenging aspects of maintaining mature, enterprise-grade Python projects.

Amen brother! :) The end-goal is the same, but right now I see a rather large challenge of making namespaced packages supported. If I can find the time, I'll have a look at the `pip <package> -t <target-dir>` command for now, it may be a root cause of the missing support.

> I seek to consolidate those efforts, deferring to the more popular and more broadly-maintained package.

That's super cool - it takes a lot of work to do that, but when the maintainer of a project reacts to the greater good of gathering community efforts behind unified efforts, we all win. Unfortunately, this can take a lot of advocacy and fail in the end. Check out how I failed here - I still don't know exactly what I did wrong, I even did all the work... opened a PR and everything :)

`https://github.com/Fantomas42/django-app-namespace-template-loader/issues/14`

**Comment by jaraco** [comment]
> I'll have a look at `pip install -t`

Have a look at [rwt #1](/jaraco/rwt/issues/1) (and possibly other tickets in that project), where I solved (hacked around) one place where this issue emerged.

> Check out how I failed here

That can be frustrating. My first three forays into open source were met with heavy resistance, and if it weren't for the local DC Python group and mentors there, I probably would have abandoned open source before I got started. Since then, I do my best to come with a good attitude, but with a bit of take-it-or-leave-it attitude, so as not to become too offended when my ideas aren't accepted. Long-winded way of saying I empathize.

**Comment by dmlb2000** [comment]
As a side note I did figure out what to do to get around this...

The application is a simple CherryPy/Celery REST style micro service. I organized the application into a single module which is where this all started...

```
setup.py
package/
    __init__.py
    __main__.py
    rest/...
    tasks/...
```

To get the entry_point working to start up the CherryPy service I put `main()` in `__init__.py`. That worked for a time, then the update came out and resulted in this stack dump. Celery was walking the `package` module as well as the `tasks` module. I run the Celery tasks as `python -m celery -A package.tasks`. So I moved the relevant imports and main method to the `__main__.py` (which is probably where it should be anyway). This cleaned up the project a bit anyway as CherryPy and Celery services don't import the high level classes but can share common classes and methods.

I found it odd that Celery is doing magic to overload the import of the `tasks` module. My guess is that if `package` was a namespace instead of a module it would not work, not tested that though.

Just my 2 cents for how I worked around the issue.

**Comment by webknjaz** [comment]
@jaraco here's another 2 cents from me :)

I did some googling and it looks like [`pkgutil.extend_path`](https://stackoverflow.com/a/1676069/595220) might become a cure for this issue.
Also, Gentoo wiki [explicitly recommends using it](https://wiki.gentoo.org/wiki/Project:Python/Namespace_packages#pkgutil.2Fsetuptools-style_namespace_packages) if the namespace package is expected to work under Python 2, which guarantees backwards compatibility.

It looks like you could try putting `from pkgutil import extend_path; __path__ = extend_path(__path__, __name__)` into `__init__.py`

I noticed that even you did some hacks to support py2exe in the past https://github.com/jaraco/jaraco.util/blob/master/jaraco/__init__.py#L5-L8 :)

**Comment by webknjaz** [comment]
Ref: https://packaging.python.org/guides/packaging-namespace-packages/#creating-a-namespace-package

This official PyPA guide also has notes about supporting cross-python compatibility.

**Comment by jaraco** [comment]
> It looks like you could try ... `pkgutil`

Yes, and I would if it weren't for the impossible compatibility issues. Note the warning in the packaging guide: 

> While native namespace packages and pkgutil-style namespace packages are largely compatible, pkg_resources-style namespace packages are not compatible with the other methods. It’s inadvisable to use different methods in different distributions that provide packages to the same namespace.

What that means is that if I switch the `jaraco` namespace to use `pkgutil` to extend the packages, I need to do it for all `jaraco*` packages and any environment that upgrades even a single one of those packages needs to upgrade all of them.

And while there are only a few packages in the public domain that rely on more than one of these, there are probably hundreds, many of which are nested and interdependent, in my company's projects.

So I've not spent the effort to transition all of those packages. If it could be shown that using pkgutil would solve most or all of these compatibility issues, that would be a strong incentive to make the switch. But otherwise, I'm more inclined to let `jaraco` (and `yg` for that matter) remain on the legacy pkg_resources-managed approach until the projects drop support for Python 3.3 and 2.7, which I expect will happen in the coming year.

**Comment by webknjaz** [comment]
Oh.. I noticed that, but didn't realize how it affects this case. I was thinking that there could probably some hack to work around it.

**Comment by webknjaz** [comment]
Also, there's:
> 3. Use pkg_resources-style namespace packages. This method is recommended if you need compatibility with packages already using this method or if your package needs to be zip-safe.


I think this means that you could use old-good `__import__('pkg_resources').declare_namespace(__name__)` to maintain compatibility within your namespace. Does this make sense?

**Comment by webknjaz** [comment]
Ooops.. I missed that it's already there.
